<?xml version="1.0" encoding="utf-8"?><Database Name="KimTravelDesktop" Class="KimTravelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=125.212.221.110;Initial Catalog=KimTravelDesktop;User ID=hoang1995" SettingsObjectName="KimTravel.DAL.Properties.Settings" SettingsPropertyName="KimTravelDesktopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ApplicationRole" Member="ApplicationRoles">
    <Type Name="ApplicationRole">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tour" Member="Tours">
    <Type Name="Tour">
      <Column Name="TourID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceSale" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceVTQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GroupTour_Tour" Member="GroupTour" ThisKey="GroupID" OtherKey="GroupID" Type="GroupTour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationUser" Member="ApplicationUsers">
    <Type Name="ApplicationUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ConfirmMail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ConfirmPhone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Locked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LockDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationUserRole" Member="ApplicationUserRoles">
    <Type Name="ApplicationUserRole">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TourID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PartnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Pax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PickUp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Room" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartnerPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceReceive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceSale" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceVTQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromotionMoney" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromotionPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StaffID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ServiceType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsCancel" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Car" Member="Cars">
    <Type Name="Car">
      <Column Name="CarID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Max" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StaffID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Staff_Car" Member="Staff" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.GroupTour" Member="GroupTours">
    <Type Name="GroupTour">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MinPax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxPax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GroupTour_Tour" Member="Tours" ThisKey="GroupID" OtherKey="GroupID" Type="Tour" />
    </Type>
  </Table>
  <Table Name="dbo.Partner" Member="Partners">
    <Type Name="Partner">
      <Column Name="PartnerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PartnerCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Partner_Staff" Member="Staffs" ThisKey="PartnerID" OtherKey="PartnerID" Type="Staff" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceType" Member="ServiceTypes">
    <Type Name="ServiceType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HotelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PartnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Kind" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PSID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Car" Member="Cars" ThisKey="ID" OtherKey="StaffID" Type="Car" />
      <Association Name="Partner_Staff" Member="Partner" ThisKey="PartnerID" OtherKey="PartnerID" Type="Partner" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="hoang1995.CarType" Member="CarTypes">
    <Type Name="CarType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="hoang1995.GroupPartner" Member="GroupPartners">
    <Type Name="GroupPartner">
      <Column Name="GroupPartnerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="hoang1995.Price" Member="Prices">
    <Type Name="Price">
      <Column Name="[Key]" Member="Key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TourID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceRe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceVTQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>